fragment PageParts on Page {
  __typename
  title
  description
  outerBgColor
  blocks {
    __typename
    ... on PageBlocksNavbar {
      logoText
      links {
        __typename
        label
        url
      }
    }
    ... on PageBlocksHero {
      heading
      subheading
    }
    ... on PageBlocksHeading {
      text
    }
    ... on PageBlocksContent {
      body
    }
    ... on PageBlocksImage {
      url
      caption
    }
    ... on PageBlocksCta {
      title
      link
    }
  }
}
