fragment PageParts on Page {
  __typename
  blocks {
    __typename
    ... on PageBlocksTextContent {
      internalName
      body
      padding {
        __typename
        top
        right
        bottom
        left
      }
      margin {
        __typename
        top
        right
        bottom
        left
      }
    }
  }
}
