//@ts-nocheck
  // DO NOT MODIFY THIS FILE. This file is automatically generated by Tina
  export function gql(strings: TemplateStringsArray, ...args: string[]): string {
    let str = ''
    strings.forEach((string, i) => {
      str += string + (args[i] || '')
    })
    return str
  }
  export type Maybe<T> = T | null;
export type InputMaybe<T> = Maybe<T>;
export type Exact<T extends { [key: string]: unknown }> = { [K in keyof T]: T[K] };
export type MakeOptional<T, K extends keyof T> = Omit<T, K> & { [SubKey in K]?: Maybe<T[SubKey]> };
export type MakeMaybe<T, K extends keyof T> = Omit<T, K> & { [SubKey in K]: Maybe<T[SubKey]> };
export type MakeEmpty<T extends { [key: string]: unknown }, K extends keyof T> = { [_ in K]?: never };
export type Incremental<T> = T | { [P in keyof T]?: P extends ' $fragmentName' | '__typename' ? T[P] : never };
/** All built-in and custom scalars, mapped to their actual values */
export type Scalars = {
  ID: { input: string; output: string; }
  String: { input: string; output: string; }
  Boolean: { input: boolean; output: boolean; }
  Int: { input: number; output: number; }
  Float: { input: number; output: number; }
  /** References another document, used as a foreign key */
  Reference: { input: any; output: any; }
  JSON: { input: any; output: any; }
};

export type SystemInfo = {
  __typename?: 'SystemInfo';
  filename: Scalars['String']['output'];
  title?: Maybe<Scalars['String']['output']>;
  basename: Scalars['String']['output'];
  hasReferences?: Maybe<Scalars['Boolean']['output']>;
  breadcrumbs: Array<Scalars['String']['output']>;
  path: Scalars['String']['output'];
  relativePath: Scalars['String']['output'];
  extension: Scalars['String']['output'];
  template: Scalars['String']['output'];
  collection: Collection;
};


export type SystemInfoBreadcrumbsArgs = {
  excludeExtension?: InputMaybe<Scalars['Boolean']['input']>;
};

export type Folder = {
  __typename?: 'Folder';
  name: Scalars['String']['output'];
  path: Scalars['String']['output'];
};

export type PageInfo = {
  __typename?: 'PageInfo';
  hasPreviousPage: Scalars['Boolean']['output'];
  hasNextPage: Scalars['Boolean']['output'];
  startCursor: Scalars['String']['output'];
  endCursor: Scalars['String']['output'];
};

export type Node = {
  id: Scalars['ID']['output'];
};

export type Document = {
  id: Scalars['ID']['output'];
  _sys?: Maybe<SystemInfo>;
  _values: Scalars['JSON']['output'];
};

/** A relay-compliant pagination connection */
export type Connection = {
  totalCount: Scalars['Float']['output'];
  pageInfo: PageInfo;
};

export type Query = {
  __typename?: 'Query';
  getOptimizedQuery?: Maybe<Scalars['String']['output']>;
  collection: Collection;
  collections: Array<Collection>;
  node: Node;
  document: DocumentNode;
  page: Page;
  pageConnection: PageConnection;
};


export type QueryGetOptimizedQueryArgs = {
  queryString: Scalars['String']['input'];
};


export type QueryCollectionArgs = {
  collection?: InputMaybe<Scalars['String']['input']>;
};


export type QueryNodeArgs = {
  id?: InputMaybe<Scalars['String']['input']>;
};


export type QueryDocumentArgs = {
  collection?: InputMaybe<Scalars['String']['input']>;
  relativePath?: InputMaybe<Scalars['String']['input']>;
};


export type QueryPageArgs = {
  relativePath?: InputMaybe<Scalars['String']['input']>;
};


export type QueryPageConnectionArgs = {
  before?: InputMaybe<Scalars['String']['input']>;
  after?: InputMaybe<Scalars['String']['input']>;
  first?: InputMaybe<Scalars['Float']['input']>;
  last?: InputMaybe<Scalars['Float']['input']>;
  sort?: InputMaybe<Scalars['String']['input']>;
  filter?: InputMaybe<PageFilter>;
};

export type DocumentFilter = {
  page?: InputMaybe<PageFilter>;
};

export type DocumentConnectionEdges = {
  __typename?: 'DocumentConnectionEdges';
  cursor: Scalars['String']['output'];
  node?: Maybe<DocumentNode>;
};

export type DocumentConnection = Connection & {
  __typename?: 'DocumentConnection';
  pageInfo: PageInfo;
  totalCount: Scalars['Float']['output'];
  edges?: Maybe<Array<Maybe<DocumentConnectionEdges>>>;
};

export type Collection = {
  __typename?: 'Collection';
  name: Scalars['String']['output'];
  slug: Scalars['String']['output'];
  label?: Maybe<Scalars['String']['output']>;
  path: Scalars['String']['output'];
  format?: Maybe<Scalars['String']['output']>;
  matches?: Maybe<Scalars['String']['output']>;
  templates?: Maybe<Array<Maybe<Scalars['JSON']['output']>>>;
  fields?: Maybe<Array<Maybe<Scalars['JSON']['output']>>>;
  documents: DocumentConnection;
};


export type CollectionDocumentsArgs = {
  before?: InputMaybe<Scalars['String']['input']>;
  after?: InputMaybe<Scalars['String']['input']>;
  first?: InputMaybe<Scalars['Float']['input']>;
  last?: InputMaybe<Scalars['Float']['input']>;
  sort?: InputMaybe<Scalars['String']['input']>;
  filter?: InputMaybe<DocumentFilter>;
  folder?: InputMaybe<Scalars['String']['input']>;
};

export type DocumentNode = Page | Folder;

export type PageBlocksNavbarLinks = {
  __typename?: 'PageBlocksNavbarLinks';
  label?: Maybe<Scalars['JSON']['output']>;
  url?: Maybe<Scalars['String']['output']>;
};

export type PageBlocksNavbar = {
  __typename?: 'PageBlocksNavbar';
  adminLabel?: Maybe<Scalars['String']['output']>;
  logoText?: Maybe<Scalars['JSON']['output']>;
  links?: Maybe<Array<Maybe<PageBlocksNavbarLinks>>>;
};

export type PageBlocksHero = {
  __typename?: 'PageBlocksHero';
  adminLabel?: Maybe<Scalars['String']['output']>;
  heading?: Maybe<Scalars['JSON']['output']>;
  subheading?: Maybe<Scalars['JSON']['output']>;
  body?: Maybe<Scalars['JSON']['output']>;
  align?: Maybe<Scalars['String']['output']>;
  textColor?: Maybe<Scalars['String']['output']>;
  fontSize?: Maybe<Scalars['Float']['output']>;
  fontWeight?: Maybe<Scalars['String']['output']>;
  pt?: Maybe<Scalars['Float']['output']>;
  pb?: Maybe<Scalars['Float']['output']>;
  pl?: Maybe<Scalars['Float']['output']>;
  pr?: Maybe<Scalars['Float']['output']>;
  mt?: Maybe<Scalars['Float']['output']>;
  mb?: Maybe<Scalars['Float']['output']>;
};

export type PageBlocksHeading = {
  __typename?: 'PageBlocksHeading';
  adminLabel?: Maybe<Scalars['String']['output']>;
  text?: Maybe<Scalars['JSON']['output']>;
  align?: Maybe<Scalars['String']['output']>;
  textColor?: Maybe<Scalars['String']['output']>;
  fontSize?: Maybe<Scalars['Float']['output']>;
  fontWeight?: Maybe<Scalars['String']['output']>;
  mt?: Maybe<Scalars['Float']['output']>;
  mb?: Maybe<Scalars['Float']['output']>;
};

export type PageBlocksContent = {
  __typename?: 'PageBlocksContent';
  adminLabel?: Maybe<Scalars['String']['output']>;
  body?: Maybe<Scalars['JSON']['output']>;
  align?: Maybe<Scalars['String']['output']>;
  textColor?: Maybe<Scalars['String']['output']>;
  fontSize?: Maybe<Scalars['Float']['output']>;
  mt?: Maybe<Scalars['Float']['output']>;
  mb?: Maybe<Scalars['Float']['output']>;
};

export type PageBlocksCta = {
  __typename?: 'PageBlocksCta';
  adminLabel?: Maybe<Scalars['String']['output']>;
  title?: Maybe<Scalars['JSON']['output']>;
  link?: Maybe<Scalars['String']['output']>;
  align?: Maybe<Scalars['String']['output']>;
  btnBgColor?: Maybe<Scalars['String']['output']>;
  btnTextColor?: Maybe<Scalars['String']['output']>;
};

export type PageBlocksImage = {
  __typename?: 'PageBlocksImage';
  adminLabel?: Maybe<Scalars['String']['output']>;
  url?: Maybe<Scalars['String']['output']>;
  caption?: Maybe<Scalars['String']['output']>;
  body?: Maybe<Scalars['JSON']['output']>;
  align?: Maybe<Scalars['String']['output']>;
};

export type PageBlocks = PageBlocksNavbar | PageBlocksHero | PageBlocksHeading | PageBlocksContent | PageBlocksCta | PageBlocksImage;

export type Page = Node & Document & {
  __typename?: 'Page';
  adminLabel: Scalars['String']['output'];
  outerBgColor?: Maybe<Scalars['String']['output']>;
  blocks?: Maybe<Array<Maybe<PageBlocks>>>;
  id: Scalars['ID']['output'];
  _sys: SystemInfo;
  _values: Scalars['JSON']['output'];
};

export type StringFilter = {
  startsWith?: InputMaybe<Scalars['String']['input']>;
  eq?: InputMaybe<Scalars['String']['input']>;
  exists?: InputMaybe<Scalars['Boolean']['input']>;
  in?: InputMaybe<Array<InputMaybe<Scalars['String']['input']>>>;
};

export type PageBlocksNavbarLogoTextColorTextFilter = {
  text?: InputMaybe<StringFilter>;
  color?: InputMaybe<StringFilter>;
};

export type PageBlocksNavbarLogoTextHighlightTextFilter = {
  text?: InputMaybe<StringFilter>;
  bgColor?: InputMaybe<StringFilter>;
  textColor?: InputMaybe<StringFilter>;
};

export type PageBlocksNavbarLogoTextFilter = {
  ColorText?: InputMaybe<PageBlocksNavbarLogoTextColorTextFilter>;
  HighlightText?: InputMaybe<PageBlocksNavbarLogoTextHighlightTextFilter>;
};

export type PageBlocksNavbarLinksLabelColorTextFilter = {
  text?: InputMaybe<StringFilter>;
  color?: InputMaybe<StringFilter>;
};

export type PageBlocksNavbarLinksLabelHighlightTextFilter = {
  text?: InputMaybe<StringFilter>;
  bgColor?: InputMaybe<StringFilter>;
  textColor?: InputMaybe<StringFilter>;
};

export type PageBlocksNavbarLinksLabelFilter = {
  ColorText?: InputMaybe<PageBlocksNavbarLinksLabelColorTextFilter>;
  HighlightText?: InputMaybe<PageBlocksNavbarLinksLabelHighlightTextFilter>;
};

export type PageBlocksNavbarLinksFilter = {
  label?: InputMaybe<PageBlocksNavbarLinksLabelFilter>;
  url?: InputMaybe<StringFilter>;
};

export type PageBlocksNavbarFilter = {
  adminLabel?: InputMaybe<StringFilter>;
  logoText?: InputMaybe<PageBlocksNavbarLogoTextFilter>;
  links?: InputMaybe<PageBlocksNavbarLinksFilter>;
};

export type PageBlocksHeroHeadingColorTextFilter = {
  text?: InputMaybe<StringFilter>;
  color?: InputMaybe<StringFilter>;
};

export type PageBlocksHeroHeadingHighlightTextFilter = {
  text?: InputMaybe<StringFilter>;
  bgColor?: InputMaybe<StringFilter>;
  textColor?: InputMaybe<StringFilter>;
};

export type PageBlocksHeroHeadingFilter = {
  ColorText?: InputMaybe<PageBlocksHeroHeadingColorTextFilter>;
  HighlightText?: InputMaybe<PageBlocksHeroHeadingHighlightTextFilter>;
};

export type PageBlocksHeroSubheadingColorTextFilter = {
  text?: InputMaybe<StringFilter>;
  color?: InputMaybe<StringFilter>;
};

export type PageBlocksHeroSubheadingHighlightTextFilter = {
  text?: InputMaybe<StringFilter>;
  bgColor?: InputMaybe<StringFilter>;
  textColor?: InputMaybe<StringFilter>;
};

export type PageBlocksHeroSubheadingFilter = {
  ColorText?: InputMaybe<PageBlocksHeroSubheadingColorTextFilter>;
  HighlightText?: InputMaybe<PageBlocksHeroSubheadingHighlightTextFilter>;
};

export type PageBlocksHeroBodyColorTextFilter = {
  text?: InputMaybe<StringFilter>;
  color?: InputMaybe<StringFilter>;
};

export type PageBlocksHeroBodyHighlightTextFilter = {
  text?: InputMaybe<StringFilter>;
  bgColor?: InputMaybe<StringFilter>;
  textColor?: InputMaybe<StringFilter>;
};

export type PageBlocksHeroBodyFilter = {
  ColorText?: InputMaybe<PageBlocksHeroBodyColorTextFilter>;
  HighlightText?: InputMaybe<PageBlocksHeroBodyHighlightTextFilter>;
};

export type NumberFilter = {
  lt?: InputMaybe<Scalars['Float']['input']>;
  lte?: InputMaybe<Scalars['Float']['input']>;
  gte?: InputMaybe<Scalars['Float']['input']>;
  gt?: InputMaybe<Scalars['Float']['input']>;
  eq?: InputMaybe<Scalars['Float']['input']>;
  exists?: InputMaybe<Scalars['Boolean']['input']>;
  in?: InputMaybe<Array<InputMaybe<Scalars['Float']['input']>>>;
};

export type PageBlocksHeroFilter = {
  adminLabel?: InputMaybe<StringFilter>;
  heading?: InputMaybe<PageBlocksHeroHeadingFilter>;
  subheading?: InputMaybe<PageBlocksHeroSubheadingFilter>;
  body?: InputMaybe<PageBlocksHeroBodyFilter>;
  align?: InputMaybe<StringFilter>;
  textColor?: InputMaybe<StringFilter>;
  fontSize?: InputMaybe<NumberFilter>;
  fontWeight?: InputMaybe<StringFilter>;
  pt?: InputMaybe<NumberFilter>;
  pb?: InputMaybe<NumberFilter>;
  pl?: InputMaybe<NumberFilter>;
  pr?: InputMaybe<NumberFilter>;
  mt?: InputMaybe<NumberFilter>;
  mb?: InputMaybe<NumberFilter>;
};

export type PageBlocksHeadingTextColorTextFilter = {
  text?: InputMaybe<StringFilter>;
  color?: InputMaybe<StringFilter>;
};

export type PageBlocksHeadingTextHighlightTextFilter = {
  text?: InputMaybe<StringFilter>;
  bgColor?: InputMaybe<StringFilter>;
  textColor?: InputMaybe<StringFilter>;
};

export type PageBlocksHeadingTextFilter = {
  ColorText?: InputMaybe<PageBlocksHeadingTextColorTextFilter>;
  HighlightText?: InputMaybe<PageBlocksHeadingTextHighlightTextFilter>;
};

export type PageBlocksHeadingFilter = {
  adminLabel?: InputMaybe<StringFilter>;
  text?: InputMaybe<PageBlocksHeadingTextFilter>;
  align?: InputMaybe<StringFilter>;
  textColor?: InputMaybe<StringFilter>;
  fontSize?: InputMaybe<NumberFilter>;
  fontWeight?: InputMaybe<StringFilter>;
  mt?: InputMaybe<NumberFilter>;
  mb?: InputMaybe<NumberFilter>;
};

export type PageBlocksContentBodyColorTextFilter = {
  text?: InputMaybe<StringFilter>;
  color?: InputMaybe<StringFilter>;
};

export type PageBlocksContentBodyHighlightTextFilter = {
  text?: InputMaybe<StringFilter>;
  bgColor?: InputMaybe<StringFilter>;
  textColor?: InputMaybe<StringFilter>;
};

export type PageBlocksContentBodyFilter = {
  ColorText?: InputMaybe<PageBlocksContentBodyColorTextFilter>;
  HighlightText?: InputMaybe<PageBlocksContentBodyHighlightTextFilter>;
};

export type PageBlocksContentFilter = {
  adminLabel?: InputMaybe<StringFilter>;
  body?: InputMaybe<PageBlocksContentBodyFilter>;
  align?: InputMaybe<StringFilter>;
  textColor?: InputMaybe<StringFilter>;
  fontSize?: InputMaybe<NumberFilter>;
  mt?: InputMaybe<NumberFilter>;
  mb?: InputMaybe<NumberFilter>;
};

export type PageBlocksCtaTitleColorTextFilter = {
  text?: InputMaybe<StringFilter>;
  color?: InputMaybe<StringFilter>;
};

export type PageBlocksCtaTitleHighlightTextFilter = {
  text?: InputMaybe<StringFilter>;
  bgColor?: InputMaybe<StringFilter>;
  textColor?: InputMaybe<StringFilter>;
};

export type PageBlocksCtaTitleFilter = {
  ColorText?: InputMaybe<PageBlocksCtaTitleColorTextFilter>;
  HighlightText?: InputMaybe<PageBlocksCtaTitleHighlightTextFilter>;
};

export type PageBlocksCtaFilter = {
  adminLabel?: InputMaybe<StringFilter>;
  title?: InputMaybe<PageBlocksCtaTitleFilter>;
  link?: InputMaybe<StringFilter>;
  align?: InputMaybe<StringFilter>;
  btnBgColor?: InputMaybe<StringFilter>;
  btnTextColor?: InputMaybe<StringFilter>;
};

export type ImageFilter = {
  startsWith?: InputMaybe<Scalars['String']['input']>;
  eq?: InputMaybe<Scalars['String']['input']>;
  exists?: InputMaybe<Scalars['Boolean']['input']>;
  in?: InputMaybe<Array<InputMaybe<Scalars['String']['input']>>>;
};

export type PageBlocksImageBodyColorTextFilter = {
  text?: InputMaybe<StringFilter>;
  color?: InputMaybe<StringFilter>;
};

export type PageBlocksImageBodyHighlightTextFilter = {
  text?: InputMaybe<StringFilter>;
  bgColor?: InputMaybe<StringFilter>;
  textColor?: InputMaybe<StringFilter>;
};

export type PageBlocksImageBodyFilter = {
  ColorText?: InputMaybe<PageBlocksImageBodyColorTextFilter>;
  HighlightText?: InputMaybe<PageBlocksImageBodyHighlightTextFilter>;
};

export type PageBlocksImageFilter = {
  adminLabel?: InputMaybe<StringFilter>;
  url?: InputMaybe<ImageFilter>;
  caption?: InputMaybe<StringFilter>;
  body?: InputMaybe<PageBlocksImageBodyFilter>;
  align?: InputMaybe<StringFilter>;
};

export type PageBlocksFilter = {
  navbar?: InputMaybe<PageBlocksNavbarFilter>;
  hero?: InputMaybe<PageBlocksHeroFilter>;
  heading?: InputMaybe<PageBlocksHeadingFilter>;
  content?: InputMaybe<PageBlocksContentFilter>;
  cta?: InputMaybe<PageBlocksCtaFilter>;
  image?: InputMaybe<PageBlocksImageFilter>;
};

export type PageFilter = {
  adminLabel?: InputMaybe<StringFilter>;
  outerBgColor?: InputMaybe<StringFilter>;
  blocks?: InputMaybe<PageBlocksFilter>;
};

export type PageConnectionEdges = {
  __typename?: 'PageConnectionEdges';
  cursor: Scalars['String']['output'];
  node?: Maybe<Page>;
};

export type PageConnection = Connection & {
  __typename?: 'PageConnection';
  pageInfo: PageInfo;
  totalCount: Scalars['Float']['output'];
  edges?: Maybe<Array<Maybe<PageConnectionEdges>>>;
};

export type Mutation = {
  __typename?: 'Mutation';
  addPendingDocument: DocumentNode;
  updateDocument: DocumentNode;
  deleteDocument: DocumentNode;
  createDocument: DocumentNode;
  createFolder: DocumentNode;
  updatePage: Page;
  createPage: Page;
};


export type MutationAddPendingDocumentArgs = {
  collection: Scalars['String']['input'];
  relativePath: Scalars['String']['input'];
  template?: InputMaybe<Scalars['String']['input']>;
};


export type MutationUpdateDocumentArgs = {
  collection?: InputMaybe<Scalars['String']['input']>;
  relativePath: Scalars['String']['input'];
  params: DocumentUpdateMutation;
};


export type MutationDeleteDocumentArgs = {
  collection?: InputMaybe<Scalars['String']['input']>;
  relativePath: Scalars['String']['input'];
};


export type MutationCreateDocumentArgs = {
  collection?: InputMaybe<Scalars['String']['input']>;
  relativePath: Scalars['String']['input'];
  params: DocumentMutation;
};


export type MutationCreateFolderArgs = {
  collection?: InputMaybe<Scalars['String']['input']>;
  relativePath: Scalars['String']['input'];
};


export type MutationUpdatePageArgs = {
  relativePath: Scalars['String']['input'];
  params: PageMutation;
};


export type MutationCreatePageArgs = {
  relativePath: Scalars['String']['input'];
  params: PageMutation;
};

export type DocumentUpdateMutation = {
  page?: InputMaybe<PageMutation>;
  relativePath?: InputMaybe<Scalars['String']['input']>;
};

export type DocumentMutation = {
  page?: InputMaybe<PageMutation>;
};

export type PageBlocksNavbarLinksMutation = {
  label?: InputMaybe<Scalars['JSON']['input']>;
  url?: InputMaybe<Scalars['String']['input']>;
};

export type PageBlocksNavbarMutation = {
  adminLabel?: InputMaybe<Scalars['String']['input']>;
  logoText?: InputMaybe<Scalars['JSON']['input']>;
  links?: InputMaybe<Array<InputMaybe<PageBlocksNavbarLinksMutation>>>;
};

export type PageBlocksHeroMutation = {
  adminLabel?: InputMaybe<Scalars['String']['input']>;
  heading?: InputMaybe<Scalars['JSON']['input']>;
  subheading?: InputMaybe<Scalars['JSON']['input']>;
  body?: InputMaybe<Scalars['JSON']['input']>;
  align?: InputMaybe<Scalars['String']['input']>;
  textColor?: InputMaybe<Scalars['String']['input']>;
  fontSize?: InputMaybe<Scalars['Float']['input']>;
  fontWeight?: InputMaybe<Scalars['String']['input']>;
  pt?: InputMaybe<Scalars['Float']['input']>;
  pb?: InputMaybe<Scalars['Float']['input']>;
  pl?: InputMaybe<Scalars['Float']['input']>;
  pr?: InputMaybe<Scalars['Float']['input']>;
  mt?: InputMaybe<Scalars['Float']['input']>;
  mb?: InputMaybe<Scalars['Float']['input']>;
};

export type PageBlocksHeadingMutation = {
  adminLabel?: InputMaybe<Scalars['String']['input']>;
  text?: InputMaybe<Scalars['JSON']['input']>;
  align?: InputMaybe<Scalars['String']['input']>;
  textColor?: InputMaybe<Scalars['String']['input']>;
  fontSize?: InputMaybe<Scalars['Float']['input']>;
  fontWeight?: InputMaybe<Scalars['String']['input']>;
  mt?: InputMaybe<Scalars['Float']['input']>;
  mb?: InputMaybe<Scalars['Float']['input']>;
};

export type PageBlocksContentMutation = {
  adminLabel?: InputMaybe<Scalars['String']['input']>;
  body?: InputMaybe<Scalars['JSON']['input']>;
  align?: InputMaybe<Scalars['String']['input']>;
  textColor?: InputMaybe<Scalars['String']['input']>;
  fontSize?: InputMaybe<Scalars['Float']['input']>;
  mt?: InputMaybe<Scalars['Float']['input']>;
  mb?: InputMaybe<Scalars['Float']['input']>;
};

export type PageBlocksCtaMutation = {
  adminLabel?: InputMaybe<Scalars['String']['input']>;
  title?: InputMaybe<Scalars['JSON']['input']>;
  link?: InputMaybe<Scalars['String']['input']>;
  align?: InputMaybe<Scalars['String']['input']>;
  btnBgColor?: InputMaybe<Scalars['String']['input']>;
  btnTextColor?: InputMaybe<Scalars['String']['input']>;
};

export type PageBlocksImageMutation = {
  adminLabel?: InputMaybe<Scalars['String']['input']>;
  url?: InputMaybe<Scalars['String']['input']>;
  caption?: InputMaybe<Scalars['String']['input']>;
  body?: InputMaybe<Scalars['JSON']['input']>;
  align?: InputMaybe<Scalars['String']['input']>;
};

export type PageBlocksMutation = {
  navbar?: InputMaybe<PageBlocksNavbarMutation>;
  hero?: InputMaybe<PageBlocksHeroMutation>;
  heading?: InputMaybe<PageBlocksHeadingMutation>;
  content?: InputMaybe<PageBlocksContentMutation>;
  cta?: InputMaybe<PageBlocksCtaMutation>;
  image?: InputMaybe<PageBlocksImageMutation>;
};

export type PageMutation = {
  adminLabel?: InputMaybe<Scalars['String']['input']>;
  outerBgColor?: InputMaybe<Scalars['String']['input']>;
  blocks?: InputMaybe<Array<InputMaybe<PageBlocksMutation>>>;
};

export type PagePartsFragment = { __typename: 'Page', adminLabel: string, outerBgColor?: string | null, blocks?: Array<{ __typename: 'PageBlocksNavbar', adminLabel?: string | null, logoText?: any | null, links?: Array<{ __typename: 'PageBlocksNavbarLinks', label?: any | null, url?: string | null } | null> | null } | { __typename: 'PageBlocksHero', adminLabel?: string | null, heading?: any | null, subheading?: any | null, body?: any | null, align?: string | null, textColor?: string | null, fontSize?: number | null, fontWeight?: string | null, pt?: number | null, pb?: number | null, pl?: number | null, pr?: number | null, mt?: number | null, mb?: number | null } | { __typename: 'PageBlocksHeading', adminLabel?: string | null, text?: any | null, align?: string | null, textColor?: string | null, fontSize?: number | null, fontWeight?: string | null, mt?: number | null, mb?: number | null } | { __typename: 'PageBlocksContent', adminLabel?: string | null, body?: any | null, align?: string | null, textColor?: string | null, fontSize?: number | null, mt?: number | null, mb?: number | null } | { __typename: 'PageBlocksCta', adminLabel?: string | null, title?: any | null, link?: string | null, align?: string | null, btnBgColor?: string | null, btnTextColor?: string | null } | { __typename: 'PageBlocksImage', adminLabel?: string | null, url?: string | null, caption?: string | null, body?: any | null, align?: string | null } | null> | null };

export type PageQueryVariables = Exact<{
  relativePath: Scalars['String']['input'];
}>;


export type PageQuery = { __typename?: 'Query', page: { __typename: 'Page', id: string, adminLabel: string, outerBgColor?: string | null, _sys: { __typename?: 'SystemInfo', filename: string, basename: string, hasReferences?: boolean | null, breadcrumbs: Array<string>, path: string, relativePath: string, extension: string }, blocks?: Array<{ __typename: 'PageBlocksNavbar', adminLabel?: string | null, logoText?: any | null, links?: Array<{ __typename: 'PageBlocksNavbarLinks', label?: any | null, url?: string | null } | null> | null } | { __typename: 'PageBlocksHero', adminLabel?: string | null, heading?: any | null, subheading?: any | null, body?: any | null, align?: string | null, textColor?: string | null, fontSize?: number | null, fontWeight?: string | null, pt?: number | null, pb?: number | null, pl?: number | null, pr?: number | null, mt?: number | null, mb?: number | null } | { __typename: 'PageBlocksHeading', adminLabel?: string | null, text?: any | null, align?: string | null, textColor?: string | null, fontSize?: number | null, fontWeight?: string | null, mt?: number | null, mb?: number | null } | { __typename: 'PageBlocksContent', adminLabel?: string | null, body?: any | null, align?: string | null, textColor?: string | null, fontSize?: number | null, mt?: number | null, mb?: number | null } | { __typename: 'PageBlocksCta', adminLabel?: string | null, title?: any | null, link?: string | null, align?: string | null, btnBgColor?: string | null, btnTextColor?: string | null } | { __typename: 'PageBlocksImage', adminLabel?: string | null, url?: string | null, caption?: string | null, body?: any | null, align?: string | null } | null> | null } };

export type PageConnectionQueryVariables = Exact<{
  before?: InputMaybe<Scalars['String']['input']>;
  after?: InputMaybe<Scalars['String']['input']>;
  first?: InputMaybe<Scalars['Float']['input']>;
  last?: InputMaybe<Scalars['Float']['input']>;
  sort?: InputMaybe<Scalars['String']['input']>;
  filter?: InputMaybe<PageFilter>;
}>;


export type PageConnectionQuery = { __typename?: 'Query', pageConnection: { __typename?: 'PageConnection', totalCount: number, pageInfo: { __typename?: 'PageInfo', hasPreviousPage: boolean, hasNextPage: boolean, startCursor: string, endCursor: string }, edges?: Array<{ __typename?: 'PageConnectionEdges', cursor: string, node?: { __typename: 'Page', id: string, adminLabel: string, outerBgColor?: string | null, _sys: { __typename?: 'SystemInfo', filename: string, basename: string, hasReferences?: boolean | null, breadcrumbs: Array<string>, path: string, relativePath: string, extension: string }, blocks?: Array<{ __typename: 'PageBlocksNavbar', adminLabel?: string | null, logoText?: any | null, links?: Array<{ __typename: 'PageBlocksNavbarLinks', label?: any | null, url?: string | null } | null> | null } | { __typename: 'PageBlocksHero', adminLabel?: string | null, heading?: any | null, subheading?: any | null, body?: any | null, align?: string | null, textColor?: string | null, fontSize?: number | null, fontWeight?: string | null, pt?: number | null, pb?: number | null, pl?: number | null, pr?: number | null, mt?: number | null, mb?: number | null } | { __typename: 'PageBlocksHeading', adminLabel?: string | null, text?: any | null, align?: string | null, textColor?: string | null, fontSize?: number | null, fontWeight?: string | null, mt?: number | null, mb?: number | null } | { __typename: 'PageBlocksContent', adminLabel?: string | null, body?: any | null, align?: string | null, textColor?: string | null, fontSize?: number | null, mt?: number | null, mb?: number | null } | { __typename: 'PageBlocksCta', adminLabel?: string | null, title?: any | null, link?: string | null, align?: string | null, btnBgColor?: string | null, btnTextColor?: string | null } | { __typename: 'PageBlocksImage', adminLabel?: string | null, url?: string | null, caption?: string | null, body?: any | null, align?: string | null } | null> | null } | null } | null> | null } };

export const PagePartsFragmentDoc = gql`
    fragment PageParts on Page {
  __typename
  adminLabel
  outerBgColor
  blocks {
    __typename
    ... on PageBlocksNavbar {
      adminLabel
      logoText
      links {
        __typename
        label
        url
      }
    }
    ... on PageBlocksHero {
      adminLabel
      heading
      subheading
      body
      align
      textColor
      fontSize
      fontWeight
      pt
      pb
      pl
      pr
      mt
      mb
    }
    ... on PageBlocksHeading {
      adminLabel
      text
      align
      textColor
      fontSize
      fontWeight
      mt
      mb
    }
    ... on PageBlocksContent {
      adminLabel
      body
      align
      textColor
      fontSize
      mt
      mb
    }
    ... on PageBlocksCta {
      adminLabel
      title
      link
      align
      btnBgColor
      btnTextColor
    }
    ... on PageBlocksImage {
      adminLabel
      url
      caption
      body
      align
    }
  }
}
    `;
export const PageDocument = gql`
    query page($relativePath: String!) {
  page(relativePath: $relativePath) {
    ... on Document {
      _sys {
        filename
        basename
        hasReferences
        breadcrumbs
        path
        relativePath
        extension
      }
      id
    }
    ...PageParts
  }
}
    ${PagePartsFragmentDoc}`;
export const PageConnectionDocument = gql`
    query pageConnection($before: String, $after: String, $first: Float, $last: Float, $sort: String, $filter: PageFilter) {
  pageConnection(
    before: $before
    after: $after
    first: $first
    last: $last
    sort: $sort
    filter: $filter
  ) {
    pageInfo {
      hasPreviousPage
      hasNextPage
      startCursor
      endCursor
    }
    totalCount
    edges {
      cursor
      node {
        ... on Document {
          _sys {
            filename
            basename
            hasReferences
            breadcrumbs
            path
            relativePath
            extension
          }
          id
        }
        ...PageParts
      }
    }
  }
}
    ${PagePartsFragmentDoc}`;
export type Requester<C= {}> = <R, V>(doc: DocumentNode, vars?: V, options?: C) => Promise<R>
  export function getSdk<C>(requester: Requester<C>) {
    return {
      page(variables: PageQueryVariables, options?: C): Promise<{data: PageQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: PageQueryVariables, query: string}> {
        return requester<{data: PageQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: PageQueryVariables, query: string}, PageQueryVariables>(PageDocument, variables, options);
      },
    pageConnection(variables?: PageConnectionQueryVariables, options?: C): Promise<{data: PageConnectionQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: PageConnectionQueryVariables, query: string}> {
        return requester<{data: PageConnectionQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: PageConnectionQueryVariables, query: string}, PageConnectionQueryVariables>(PageConnectionDocument, variables, options);
      }
    };
  }
  export type Sdk = ReturnType<typeof getSdk>;

// TinaSDK generated code
import { createClient, TinaClient } from "tinacms/dist/client";

const generateRequester = (
  client: TinaClient,
) => {
  const requester: (
    doc: any,
    vars?: any,
    options?: {
      branch?: string,
      /**
       * Aside from `method` and `body`, all fetch options are passed
       * through to underlying fetch request
       */
      fetchOptions?: Omit<Parameters<typeof fetch>[1], 'body' | 'method'>,
    },
    client
  ) => Promise<any> = async (doc, vars, options) => {
    let url = client.apiUrl
    if (options?.branch) {
      const index = client.apiUrl.lastIndexOf('/')
      url = client.apiUrl.substring(0, index + 1) + options.branch
    }
    const data = await client.request({
      query: doc,
      variables: vars,
      url,
    }, options)

    return { data: data?.data, errors: data?.errors, query: doc, variables: vars || {} }
  }

  return requester
}

/**
 * @experimental this class can be used but may change in the future
 **/
export const ExperimentalGetTinaClient = () =>
  getSdk(
    generateRequester(
      createClient({
        url: "http://localhost:4001/graphql",
        queries,
      })
    )
  )

export const queries = (
  client: TinaClient,
) => {
  const requester = generateRequester(client)
  return getSdk(requester)
}

  